const keys = [
    {
        code: 'Backquote',
        lover: { en: '`', ru: 'ё' },
        upper: { en: '~', ru: 'Ё' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit1',
        lover: { en: '1', ru: '1' },
        upper: { en: '!', ru: '!' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit2',
        lover: { en: '2', ru: '2' },
        upper: { en: '@', ru: '"' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit3',
        lover: { en: '3', ru: '3' },
        upper: { en: '#', ru: '№' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit4',
        lover: { en: '4', ru: '4' },
        upper: { en: '$', ru: ';' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit5',
        lover: { en: '5', ru: '5' },
        upper: { en: '%', ru: '%' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit6',
        lover: { en: '6', ru: '6' },
        upper: { en: '^', ru: ':' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit7',
        lover: { en: '7', ru: '7' },
        upper: { en: '&', ru: '?' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit8',
        lover: { en: '8', ru: '8' },
        upper: { en: '*', ru: '*' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit9',
        lover: { en: '9', ru: '9' },
        upper: { en: '(', ru: '(' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Digit0',
        lover: { en: '0', ru: '0' },
        upper: { en: ')', ru: ')' },
        character: { en: 'digit', ru: 'digit' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Minus',
        lover: { en: '-', ru: '-' },
        upper: { en: '_', ru: '_' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Equal',
        lover: { en: '=', ru: '=' },
        upper: { en: '+', ru: '+' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_1',
    },
    {
        code: 'Backspace',
        lover: { en: 'Backspace', ru: 'Backspace' },
        upper: { en: 'Backspace', ru: 'Backspace' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_double',
        line: 'line_1',
    },
    {
        code: 'Tab',
        lover: { en: 'Tab', ru: 'Tab' },
        upper: { en: 'Tab', ru: 'Tab' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyQ',
        lover: { en: 'q', ru: 'й' },
        upper: { en: 'Q', ru: 'Й' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyW',
        lover: { en: 'w', ru: 'ц' },
        upper: { en: 'W', ru: 'Ц' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyE',
        lover: { en: 'e', ru: 'у' },
        upper: { en: 'E', ru: 'У' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyR',
        lover: { en: 'r', ru: 'к' },
        upper: { en: 'R', ru: 'К' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyT',
        lover: { en: 't', ru: 'е' },
        upper: { en: 'T', ru: 'Е' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyY',
        lover: { en: 'y', ru: 'н' },
        upper: { en: 'Y', ru: 'Н' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyU',
        lover: { en: 'u', ru: 'г' },
        upper: { en: 'U', ru: 'Г' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyI',
        lover: { en: 'i', ru: 'ш' },
        upper: { en: 'I', ru: 'Ш' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyO',
        lover: { en: 'o', ru: 'щ' },
        upper: { en: 'O', ru: 'Щ' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'KeyP',
        lover: { en: 'p', ru: 'з' },
        upper: { en: 'P', ru: 'З' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'BracketLeft',
        lover: { en: '[', ru: 'х' },
        upper: { en: '{', ru: 'Х' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'BracketRight',
        lover: { en: ']', ru: 'ъ' },
        upper: { en: '}', ru: 'Ъ' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'Backslash',
        lover: { en: '\\', ru: '\\' },
        upper: { en: '|', ru: '/' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'Delete',
        lover: { en: 'Del', ru: 'Del' },
        upper: { en: 'Del', ru: 'Del' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_2',
    },
    {
        code: 'CapsLock',
        lover: { en: 'CapsLock', ru: 'CapsLock' },
        upper: { en: 'CapsLock', ru: 'CapsLock' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_double',
        line: 'line_3',
    },
    {
        code: 'KeyA',
        lover: { en: 'a', ru: 'ф' },
        upper: { en: 'A', ru: 'Ф' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyS',
        lover: { en: 's', ru: 'ы' },
        upper: { en: 'S', ru: 'Ы' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyD',
        lover: { en: 'd', ru: 'в' },
        upper: { en: 'D', ru: 'В' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyF',
        lover: { en: 'f', ru: 'а' },
        upper: { en: 'F', ru: 'А' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyG',
        lover: { en: 'g', ru: 'п' },
        upper: { en: 'G', ru: 'П' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyH',
        lover: { en: 'h', ru: 'р' },
        upper: { en: 'H', ru: 'Р' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyJ',
        lover: { en: 'j', ru: 'о' },
        upper: { en: 'J', ru: 'О' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyK',
        lover: { en: 'k', ru: 'л' },
        upper: { en: 'K', ru: 'Л' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'KeyL',
        lover: { en: 'l', ru: 'д' },
        upper: { en: 'L', ru: 'Д' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'Semicolon',
        lover: { en: ';', ru: 'ж' },
        upper: { en: ':', ru: 'Ж' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'Quote',
        lover: { en: "'", ru: 'э' },
        upper: { en: '"', ru: 'Э' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_3',
    },
    {
        code: 'Enter',
        lover: { en: 'Enter', ru: 'Enter' },
        upper: { en: 'Enter', ru: 'Enter' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_double',
        line: 'line_3',
    },
    {
        code: 'ShiftLeft',
        lover: { en: 'Shift', ru: 'Shift' },
        upper: { en: 'Shift', ru: 'Shift' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_double',
        line: 'line_4',
    },
    {
        code: 'KeyZ',
        lover: { en: 'z', ru: 'я' },
        upper: { en: 'Z', ru: 'Я' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyX',
        lover: { en: 'x', ru: 'ч' },
        upper: { en: 'X', ru: 'Ч' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyC',
        lover: { en: 'c', ru: 'с' },
        upper: { en: 'C', ru: 'С' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyV',
        lover: { en: 'v', ru: 'м' },
        upper: { en: 'V', ru: 'М' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyB',
        lover: { en: 'b', ru: 'и' },
        upper: { en: 'B', ru: 'И' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyN',
        lover: { en: 'n', ru: 'т' },
        upper: { en: 'N', ru: 'Т' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'KeyM',
        lover: { en: 'm', ru: 'ь' },
        upper: { en: 'M', ru: 'Ь' },
        character: { en: 'letter', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'Comma',
        lover: { en: ',', ru: 'б' },
        upper: { en: '<', ru: 'Б' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'Period',
        lover: { en: '.', ru: 'ю' },
        upper: { en: '>', ru: 'Ю' },
        character: { en: 'symbol', ru: 'letter' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'Slash',
        lover: { en: '/', ru: '.' },
        upper: { en: '?', ru: ',' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'ArrowUp',
        lover: { en: '↑', ru: '↑' },
        upper: { en: '↑', ru: '↑' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_4',
    },
    {
        code: 'ShiftRight',
        lover: { en: 'Shift', ru: 'Shift' },
        upper: { en: 'Shift', ru: 'Shift' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_double',
        line: 'line_4',
    },
    {
        code: 'ControlLeft',
        lover: { en: 'Ctrl', ru: 'Ctrl' },
        upper: { en: 'Ctrl', ru: 'Ctrl' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'AltLeft',
        lover: { en: 'Alt', ru: 'Alt' },
        upper: { en: 'Alt', ru: 'Alt' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'Space',
        lover: { en: ' ', ru: ' ' },
        upper: { en: ' ', ru: ' ' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_space',
        line: 'line_5',
    },
    {
        code: 'AltRight',
        lover: { en: 'Alt', ru: 'Alt' },
        upper: { en: 'Alt', ru: 'Alt' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'ArrowLeft',
        lover: { en: '←', ru: '←' },
        upper: { en: '←', ru: '←' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'ArrowDown',
        lover: { en: '↓', ru: '↓' },
        upper: { en: '↓', ru: '↓' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'ArrowRight',
        lover: { en: '→', ru: '→' },
        upper: { en: '→', ru: '→' },
        character: { en: 'symbol', ru: 'symbol' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
    {
        code: 'ControlRight',
        lover: { en: 'Ctrl', ru: 'Ctrl' },
        upper: { en: 'Ctrl', ru: 'Ctrl' },
        character: { en: 'func', ru: 'func' },
        size: 'key_btn_size_standart',
        line: 'line_5',
    },
];

export default keys;
